name: Create flytekit-java release
on:
  workflow_dispatch:
    inputs:
      version:
        description: "version name. example 0.1.1"
        required: true
      snapshot:
        description: "snapshot version name. example 0.2.0-SNAPSHOT"
        required: true

jobs:
  build-snapshot:
    runs-on: ubuntu-latest
    name: flytekit-java release
    steps:
      - uses: actions/checkout@v2
        with:
          ref: "master"
          fetch: "0"

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-prepare-release-${{ hashFiles('pom.xml') }}

      - uses: crazy-max/ghaction-import-gpg@v3
        with:
          gpg-private-key: ${{ secrets.FLYTE_BOT_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.FLYTE_BOT_GPG_PASSPHRASE }}
          git-user-signingkey: true
          git-commit-gpgsign: true

      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11.0
          distribution: 'adopt'
          server-id: snapshots

      - name: Prepare Release
        run: |
          mvn --batch-mode release:update-versions -DdevelopmentVersion=${{ github.event.inputs.version }} -DgenerateBackupPoms=false
          git add **/*.xml
          git commit -am "Set version numbers to ${{ github.event.inputs.version }}"
          git push origin master

      - uses: actions/checkout@v2
        with:
          ref: "master"
          fetch: "0"

      - name: Bump version and push tag
        id: bump-version
        uses: anothrNick/github-tag-action@1.17.2
        env:
          GITHUB_TOKEN: ${{ secrets.FLYTE_BOT_PAT }}
          WITH_V: true
          CUSTOM_TAG: ${{ github.event.inputs.version }}
          RELEASE_BRANCHES: master

      - uses: actions/checkout@v2
        with:
          ref: "master"
          fetch: "0"

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.FLYTE_BOT_USERNAME }}
          password: ${{ secrets.FLYTE_BOT_PAT }}

      - name: Release snapshot with Maven
        run: mvn --batch-mode release  -DpreparationGoals=clean -Ddockerfile.push
        env:
          RELEASE_REPOSITORY_URL: "https://s01.oss.sonatype.org/service/local/staging/deploy/maven2/"
          SNAPSHOTS_REPOSITORY_URL: "https://s01.oss.sonatype.org/content/repositories/snapshots"
          MAVEN_USERNAME: flytekit
          MAVEN_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}

      - name: Prepare Snapshot
        run: |
          mvn versions:set -DnewVersion=${{ github.event.inputs.snapshot }}-SNAPSHOT -DgenerateBackupPoms=false
          git add **/*.xml
          git commit -am "Set version numbers to ${{ github.event.inputs.snapshot }}-SNAPSHOT"
          git push origin master